# Foundation Organizational Units
# Core OUs required for AWS SRA compliance

Security:
  lifecycle: prod
  description: "Security and compliance accounts (log archive, audit, security tooling)"
  additional_tags:
    Purpose: "Security"
    Compliance: "Required"

Policy_Staging:
  lifecycle: nonprod
  description: "Policy testing and validation"
  additional_tags:
    Purpose: "Policy Testing"
    Environment: "NonProd"

Suspended:
  lifecycle: nonprod
  description: "Suspended or decommissioned accounts"
  additional_tags:
    Purpose: "Account Lifecycle Management"
    Status: "Suspended"
