# Foundation Account - AWS Organization Management Account
# CRITICAL: This must be the AWS Organization management account

management_account:
  account_id: "123456789012" # UPDATE: Your actual management account ID
  account_name: "YourOrg-Management" # UPDATE: Exact name from CLI creation
  email: "aws-mgmt@yourorg.com" # UPDATE: Exact email from CLI creation
  account_type: management # REQUIRED: Must be "management"
  ou: Root # REQUIRED: Management account must be in Root OU
  lifecycle: prod
  additional_tags:
    Owner: "Platform Team"
    Purpose: "AWS Organization Management"
    Critical: "true"
