# Infrastructure Accounts
# Network, shared services, and connectivity accounts

network_account:
  account_id: "456789012345" # UPDATE: Your actual network account ID
  account_name: "YourOrg-Network-Hub" # UPDATE: Exact name from CLI creation
  email: "aws-network@yourorg.com" # UPDATE: Exact email from CLI creation
  account_type: network # Network/connectivity account
  ou: Infrastructure_Prod # Infrastructure OU for production
  lifecycle: prod
  additional_tags:
    Owner: "Network Team"
    Purpose: "Transit Gateway and Network Hub"
    Environment: "production"

shared_services_account:
  account_id: "567890123456" # UPDATE: Your actual shared services account ID
  account_name: "YourOrg-SharedServices-Prod" # UPDATE: Exact name from CLI creation
  email: "aws-shared@yourorg.com" # UPDATE: Exact email from CLI creation
  account_type: shared_services # Shared services account
  ou: Infrastructure_Prod # Infrastructure OU for production
  lifecycle: prod
  additional_tags:
    Owner: "Platform Team"
    Purpose: "Shared Infrastructure Services"
    Environment: "production"
