# Security Foundational Accounts
# Required by AWS Control Tower for security and compliance

log_archive_account:
  account_id: "234567890123" # UPDATE: Your actual log archive account ID
  account_name: "YourOrg-Security-LogArchive" # UPDATE: Exact name from CLI creation
  email: "aws-logs@yourorg.com" # UPDATE: Exact email from CLI creation
  account_type: log_archive # REQUIRED: Must be "log_archive"
  ou: Security # REQUIRED: Must be in Security OU
  lifecycle: prod
  additional_tags:
    Owner: "Security Team"
    Purpose: "Centralized Logging"
    DataRetention: "7-years"
    Compliance: "Required"

audit_account:
  account_id: "345678901234" # UPDATE: Your actual audit account ID
  account_name: "YourOrg-Security-Audit" # UPDATE: Exact name from CLI creation
  email: "aws-audit@yourorg.com" # UPDATE: Exact email from CLI creation
  account_type: audit # REQUIRED: Must be "audit"
  ou: Security # REQUIRED: Must be in Security OU
  lifecycle: prod
  additional_tags:
    Owner: "Security Team"
    Purpose: "Security Audit & Compliance"
    Compliance: "Required"
    GuardDuty: "DelegatedAdmin"
    SecurityHub: "DelegatedAdmin"
