# SSO Account Assignments
# Maps account names to their SSO group assignments based on account type

account_assignments:
  # Management account - administrative access only
  "SCCA Root":
    account_type: management
    groups:
      - aws_admin

  # Security accounts - admin + security groups
  "nmmes-zt-test-logging":
    account_type: log_archive
    groups:
      - aws_admin
      - aws_cyber_sec_eng
      - aws_sec_auditor

  "nmmes-zt-test-auth":
    account_type: audit
    groups:
      - aws_admin
      - aws_cyber_sec_eng
      - aws_sec_auditor

  # Network account - comprehensive access for infrastructure management
  "nmmes-zt-test-transit":
    account_type: network
    groups:
      - aws_admin
      - aws_net_admin
      - aws_sys_admin
      - aws_power_user
      - aws_cyber_sec_eng
      - aws_sec_auditor

  # Workload account - standard application access
  "nmmes-zt-test-app":
    account_type: workload
    groups:
      - aws_admin
      - aws_sys_admin
      - aws_power_user
