# Foundation Management Account
# See: /docs/account-management-guide.md for detailed instructions

management_account:
  account_id: "227234344980"
  account_name: "SCCA Root"
  email: "nmmes-scca-test-org-root@stigian.com"
  account_type: management # Maps to AccountType tag
  ou: Root # Management account at root level
  lifecycle: prod
  additional_tags:
    Owner: "Central IT"
    Purpose: "Organization Management"
    Compliance: "Required"
