# Network and Infrastructure Accounts
# Accounts for shared networking and infrastructure services

network_account:
  account_id: "261500508709"
  account_name: "nmmes-zt-test-transit"
  email: "nmmes-zt-test-transit@stigian.com"
  account_type: network # Maps to AccountType tag
  ou: Infrastructure_Test # Network connectivity infrastructure
  lifecycle: test
  additional_tags:
    Owner: "Network Team"
    Purpose: "Transit Gateway & Network Hub"
    Environment: "Test"
