# Security Control Accounts
# See: /docs/account-management-guide.md for detailed instructions

log_archive_account:
  account_id: "261503748007"
  account_name: "nmmes-zt-test-logging"
  email: "nmmes-zt-test-logging@stigian.com"
  account_type: log_archive # Maps to AccountType tag
  ou: Security # Centralized logging
  lifecycle: prod
  additional_tags:
    Owner: "Security Team"
    Purpose: "Centralized Logging"
    DataRetention: "7-years"

audit_account:
  account_id: "261523644253"
  account_name: "nmmes-zt-test-auth"
  email: "nmmes-zt-test-auth@stigian.com"
  account_type: audit # Maps to AccountType tag
  ou: Security # Audit and compliance
  lifecycle: prod
  additional_tags:
    Owner: "Security Team"
    Purpose: "Security Audit & Compliance"
    Compliance: "Required"
# Add more security accounts here (SIEM, security tools, etc.)
# All security accounts use Security OU with prod lifecycle
