# Security Foundational Accounts
# Required by AWS Control Tower for security and compliance

log_archive_account:
  account_id: "261503748007"
  account_name: "nmmes-zt-test-logging"
  email: "nmmes-zt-test-logging@stigian.com"
  account_type: log_archive # Maps to AccountType tag
  ou: Security # Required: Must be in Security OU
  lifecycle: prod
  additional_tags:
    Owner: "Security Team"
    Purpose: "Centralized Logging"
    DataRetention: "7-years"

audit_account:
  account_id: "261523644253"
  account_name: "nmmes-zt-test-auth"
  email: "nmmes-zt-test-auth@stigian.com"
  account_type: audit # Maps to AccountType tag
  ou: Security # Required: Must be in Security OU
  lifecycle: prod
  additional_tags:
    Owner: "Security Team"
    Purpose: "Security Audit & Compliance"
    Compliance: "Required"
