# Application Workload Accounts
# See: /docs/account-management-guide.md for detailed instructions

# Current workload account
nmmes_zt_test_app:
  account_id: "261632763096"
  account_name: "nmmes-zt-test-app"
  email: "nmmes-zt-test-app@stigian.com"
  account_type: workload # Maps to AccountType tag
  ou: Workloads_NonProd # NonProd workload organizational unit
  lifecycle: nonprod
  additional_tags:
    Owner: "Application Team"
    Purpose: "Application Workloads"
    Environment: "Test"
# To add more workload accounts:
# 1. Create account via CLI first: aws organizations create-gov-cloud-account
# 2. Add new entry below with unique key and account ID from CLI
# 3. Choose OU: Workloads_Prod (prod) or Workloads_NonProd (nonprod)
# 4. Run: tofu plan && tofu apply
#
# Example:
# my_new_app:
#   account_id: "123456789012"  # From CLI creation
#   account_name: "MyApp-Production"
#   email: "myapp-prod@yourorg.com"
#   account_type: workload
#   ou: Workloads_Prod
#   lifecycle: prod
#   additional_tags:
#     Owner: "MyApp Team"
