# Foundation Organizational Units
# Core OUs required by AWS SRA and Control Tower

Security:
  lifecycle: prod
  additional_tags:
    Purpose: "Security and compliance accounts"
    Owner: "Security Team"
    Criticality: "High"

Root:
  lifecycle: prod
  additional_tags:
    Purpose: "Organization root - management account only"
    Owner: "Platform Team"
    Criticality: "Critical"
