# Workload Organizational Units
# For application and business workload accounts

Workloads_Prod:
  lifecycle: prod
  additional_tags:
    Purpose: "Production application workloads"
    Owner: "Application Teams"
    Environment: "production"
    Criticality: "High"

Workloads_NonProd:
  lifecycle: nonprod
  additional_tags:
    Purpose: "Non-production application workloads"
    Owner: "Application Teams"
    Environment: "nonprod"
    Criticality: "Medium"

Sandbox:
  lifecycle: nonprod
  additional_tags:
    Purpose: "Development and experimentation"
    Owner: "Development Teams"
    Environment: "sandbox"
    Criticality: "Low"
    AutoCleanup: "enabled"

Policy_Staging:
  lifecycle: nonprod
  additional_tags:
    Purpose: "Policy testing and validation"
    Owner: "Platform Team"
    Environment: "staging"
    Criticality: "Medium"

Suspended:
  lifecycle: nonprod
  additional_tags:
    Purpose: "Decommissioned accounts"
    Owner: "Platform Team"
    Status: "suspended"
    Criticality: "None"
