name: Checkov

on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions: read-all # CKV2_GHA_1: Ensure top-level permissions are not set to write-all

jobs:
  scan:
    name: Scan Terraform
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          output_file_path: console,results.sarif
          config_file: ${{ github.workspace }}/.github/checkov-config.yml

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3

        # Results are generated only on a success or failure
        # this is required since GitHub by default won't run the next step
        # when the previous one has failed. Security checks that do not pass will 'fail'.
        # An alternative is to add `continue-on-error: true` to the previous step
        # Or 'soft_fail: true' to checkov.
        if: success() || failure()
        with:
          sarif_file: results.sarif